### ISSUE TITLE
Conflict with other modals

### ISSUE THREAD

**Issue by simonflick** [mediaconcept/sw6-plugin-cookie-permission#1]
If the extension is used in combination with the [Gross / net price switcher](https://store.shopware.com/en/maxia71914170492/gross/net-price-switcher.html) extension and both modals show up there is a style conflict as they have the same z-index. The cookie modal and its background should have a slightly higher z-index.

I have fixed that in the theme already but then there is another problem: both modals use an element to darken the background. But if the cookie banner is submitted it removes both backgrounds.

**Comment by srusche** [comment]
Sorry, I didn't see your issue until now. Most users write tickets via Shopware account. Now I enabled notifications for me.

In general, it is difficult to be compatible with every available plugin. We therefore try to stay as close as possible to the standard and only make really necessary adjustments.
The behaviour of how the modal is opened/closed and the showing/hiding of the backdrop was not adapted here. So in the standard Shopware it should show the same behaviour (when opening "configure cookies"). I think it's an individual problem and probably solved by now?
