### ISSUE TITLE
Please complete/push Tags here.

### ISSUE THREAD

**Issue by jonas-sfx** [mediaconcept/sw6-plugin-cookie-permission#3]
Thank you for providing your module open source on GitHub. :smile: 

You once provided the tag of version 1.0.0 correctly.
But your versions 1.1.0, 1.2.0, 1.3.0, 1.3.1 and 1.4.0 are not yet provided as tags (yet).
Pushing that tags from your local repos to this one could help.

**Comment by srusche** [comment]
Okay, I added and pushed version tags.
